### ISSUE TITLE
Fieldset css classes

### ISSUE THREAD

**Issue by vojtatranta** [matllubos/django-is-core#127]
It would be nice for styling if we could add css classes to fieldset.
Now we cannot style fieldset easily, because all of them have similar classes (with-title).

Like this for example:
```
return ( 
    (_('Contact information'), 'my-brilliant-css-class', {
        'fields': ('contact_person', 'phone', 'bank_account_prefix', 'bank_account_number', 'bank_code')
    }),
)
```

**Comment by matllubos** [comment]
It exists. For this purpose is fields inside dict.

return ( 
    (_('Contact information'), 'my-brilliant-css-class', {
        'fields': ('contact_person', 'phone', 'bank_account_prefix', 'bank_account_number', 'bank_code'),
        'class': 'your-brilliant-css-class'
    }),
)
```

**Comment by vojtatranta** [comment]
Ahaa, brilliant.

**Comment by vojtatranta** [comment]
That's solved then.
