### ISSUE TITLE
Better name for this lib

### ISSUE THREAD

**Issue by vojtatranta** [matllubos/django-is-core#151]
As Amber said during PyCon2015, is-core should have better name, more pythonic, any ideas?

**Comment by matllubos** [comment]
Good point, firstly we must find name for piston. Piston is Píst so we can use Cylinder (válec). Better idea?

**Comment by matllubos** [comment]
BTW. Thanks for the interest

**Comment by vojtatranta** [comment]
Pisston!

**Comment by LukasRychtecky** [comment]
We're about to change it in January.
