### ISSUE TITLE
Kontrolovat v chamberu u ChoicesNumEnum, že klíč nemá whitespace

### ISSUE THREAD

**Issue by asgeirrr** [matllubos/django-is-core#152]
Stalo se, že Ondra dal jako klíč enumu 'IN PROGRESS' a já pak v kódu jak blbec dával 'IN_PROGRESS' a hrozně jsem se divil.

P.S. Dávám to sem, protože repozitář chamberu nemá issues, ale potřebuju to někam napsat, abych nezapomněl.

**Comment by LukasRychtecky** [comment]
https://github.com/matllubos/django-chamber/issues/7
